-- 코드를 입력하세요
SELECT ANIMAL_ID,NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID


# SELECT I.ANIMAL_ID, I.NAME,I.DATETIME, O.DATETIME
# FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.NAME IS NULL